### PR TITLE
Move over to psm to provide stack switching

### PR DESCRIPTION
**Pull request by nagisa**
`psm` is a crate that implements stack switching and introspection on most of the architectures and platforms that Rust supports. Check its [readme](https://github.com/nagisa/psm#platform-support) to see platforms supported.

Notably absent from the list there are support for stack switching on Windows, for the same reason why this crate is using fibers. I’m still looking into how to make unwinding work without fibers, but since full fiber implementation is already here, I see no reason whatsoever to delay implementation for other architectures/platforms.

cc @oli-obk

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'm personally wary to shard such a hairy crate like this across multiple crates, I think that'd just make things more difficult than it needs to be to keep things in sync. I don't personally feel the need to continue maintaining the crate if the compiler team wants more of a hand in it and I don't mind transferring elsewhere if that'd be easiest. Do you have a preference?

**Comment by nagisa** [comment]
I chose to extract assembly into a separate crate because I (personally, not as a part of T-compiler) expect to eventually create a different approach to effectively infinite stacks as a competing approach to what is proposed by stacker.

I would be open with having `psm` as a subdirectory yet still a-different-crate in a same directory. That would keep the two crates in sync still. Making this a T-compiler project (seeing as we expect to make compiler first major user of the crate) also seems good to me.

**Comment by alexcrichton** [comment]
Sounds like a good idea to me! Sharing the low-level bits for two technically different approaches sounds like a the way to go. I agree though it's best to develop everything all in the same repository rather than across a few. 

I'm up for whatever T-compiler or you would prefer in terms of organization!

**Comment by nagisa** [comment]
> I don't see how splitting just the assembly into a different crate helps here. If we want to move to an infinite stack system, wouldn't the API be a completely different one? Or would it still be the same API but instead of bumping the stack size we'd do the infinite stack stuff?

The assembly files (and the wrapper over them – psm) provide the primitive operations – changing the stack pointer, executing stuff on the new stack, restoring the stack pointer on return, reading back the stack pointer, etc. Those primitives do not concern themselves with how stack is allocated or managed at all, which then allows multiple alternative solutions in that area. 

`stacker` is one such solution – indeed this PR reduces its responsibilities (outside of the Windows implementation, for now) down to stack allocation and tracking of those allocations. The "infinite" stack solution I’m envisioning would still need an ability to switch to an alternate stack(s) – it isn’t always possible to supply a custom stack during thread’s creation.

The API of these primitives provided by `psm` may change slightly over time to account for platform realities or in case the current API is not flexible enough, but none of that should end up being leaked outside a crate (stacker & friends) that deals with the higher-level concerns.

**Comment by oli-obk** [comment]
Ok, if there are expected to be other users of the primitives, a separate crate sounds like the way to go.

**Comment by nagisa** [comment]
Just heads up, we’ll likely discuss how T-compiler will want to do T-compiler-managed crates during the All Hands. I expect this PR to stay in limbo till then.

As an update, I got Windows support mostly working, so we may eventually have an option of getting ourselves free from fibers. There is only hiccup where in appveyor’s environment none of the SEH handlers are considered despite them all being in the right places & the same thing working locally.

**Comment by nagisa** [comment]
I do not think we ended up arriving at a particular location different from what we're used to currently (rust-lang/rust-lang-nursery).

I'll publish a new version of `psm` with a partial windows (64-bit only) support and import the crate in-tree once things get calmer (hopefully this or next weekend). We can then move the crate/add maintainers/transfer ownership or maintainership (I’ll gladly maintain).

**Comment by nagisa** [comment]
The current CI failures appear to be a CI issue, not code issue except for WASM for which the pre-built library is now outdated.

**Comment by alexcrichton** [comment]
I think I don't personally have the time to maintain this crate any more, but should I perhaps transfer it to rust-lang if the compiler team wants to take over?

**Comment by nagisa** [comment]
I would be willing to take over myself even if T-compiler as a whole does not.

**Comment by alexcrichton** [comment]
Ok! Would you have a preference of transferring this repository to you or rust-lang? If I transfer to you I think you'll need to delete your fork first

**Comment by nagisa** [comment]
We discussed it briefly in the [compiler team meeting](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-07-25.20.2354818/near/171696665) and it seems like we were fine with having the crate under `rust-lang`. It would be great if you could move it there and add the compiler team as a maintainer for the crate.

**Comment by alexcrichton** [comment]
Ok I've transferred to `rust-lang` and configured the compiler team to be an admin of the repository. I've added the compiler team as an owner on crates.io as well as inviting you as an owner as well. Would you like me to enable Azure Pipelines for CI? I think Travis will pick up the rename eventually but AppVeyor won't work after a rename unless something is reconfigured.

**Comment by nagisa** [comment]
Yeah, it would be cool if you enabled Azure Pipelines, I will write some config for it at some point then.

**Comment by alexcrichton** [comment]
Ok I've added you as an admin on https://dev.azure.com/rust-lang/stacker/ and you should be able to take it from there in terms of configuration

**Comment by nagisa** [comment]
Merged into master. Will still need some fiddling before the library is ready for a release but we are getting there!

**Pull request closed without merging**
