### PR TITLE
Bump cc dependency

### PR DESCRIPTION
**Pull request by arttet**
Closes https://github.com/rust-lang/stacker/issues/100

### CODE REVIEW

**Comment by nagisa** [comment]
Can't the Rust project bump the version in the lockfile? In principle there isn't anything wrong with (some?) older versions of `cc` in combination with (some?) older versions of MacOS and/or Rust toolchain.

**Comment by arttet** [comment]
> Can't the Rust project bump the version in the lockfile? 

We can do it, but it will be a workaround. If we want to fix the issue, we should bump this dependency.

> In principle there isn't anything wrong with (some?) older versions of cc in combination with (some?) older versions of MacOS and/or Rust toolchain.

In general, older versions of `cc` cannot work with older versions of ARM64e macOS.
For example, we can build that target for 11 `macOS`.

**Comment by arttet** [comment]
Hi @nagisa,

I've reviewed this issue once more. Unfortunately, at the moment, I can only override the version for all dependencies and not specifically for this library, which is not what I need. Therefore, I've concluded that merging this PR is the only way to resolve the issue. I would appreciate it if you could review this PR again, as this issue is a blocker for me.

**Comment by nagisa** [comment]
Alright, I don't care super much either way.

I still don't follow your line of reasoning -- to me maintaining the lock file in a way that ensures project's functional requirements doesn't sound like a hack at all. I'm personally a strong believer that `Cargo.toml` dependency specifications should only reflect library API compatibility and nothing else (in most cases.) Besides, it looks like `rust-lang/rust` is already locking `cc` to `1.1.23` which is higher than the dependency specification PRd here, and there's only one copy of `cc` shared between all dependencies, so ultimately I don't really see what is being achieved here… Perhaps maybe only that you might now be able to build rustc with `-Zminimal-versions` on `arm64e-macos`? Is that the use-case?

**Comment by arttet** [comment]
Yes, it has already merged in Rust. I didn't see [that MR](https://github.com/rust-lang/rust/pull/131070). Anyway, thank you.

**Pull request merged**
